version: '1.0.{build}'
#assembly_info:
#  patch: true
#  file: '**\*.csproj'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: 5.0.3
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: TestingLab1.sln
#dotnet: 5.0.300
#script:
#    - dotnet restore
#    - dotnet build
#    - dotnet test TestingLab1.csproj