version: '1.0.{build}'
assembly_info:
  patch: true
  file: Program.cs
mono: none
sudo: required
dist: xenial
dotnet: 5.0.300
os:
- windows
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/NosCore.Tests/NosCore.Tests.csproj