version: '1.0.{build}'
assembly_info:
  patch: true
  file: TestingLab1.csproj
build:
  project: TestingLab1.sln
#dotnet: 5.0.300
#script:
#    - dotnet restore
#    - dotnet build
#    - dotnet test TestingLab1.csproj